### ISSUE TITLE
I.createMailbox create empty address

### ISSUE THREAD

**Issue by aelzhanova** [HughZurname/codeceptjs-tempmail#1]
MyCode:
```js
Scenario.only('Users', function* (I, loginPage, usersPage) {
  I.createMailbox('');
  testUser.email = yield I.getMailbox();
  console.log(testUser.email);
  });
```

Actual Result:
console.log(testUser.email) returns me { address: '', messages: [] }. 

Expected result:

> createMailbox
> 
> Parameters
> 
> name string? Optional string to be used in mainlbox address
> Examples
```js
I.createMailbox('testmail') //{address: "testmail@doanart.com", messages: {error: "there are no messages yet"}}
I.createMailbox() //{address: "taij1q1j8n8@doanart.com", messages: {error: "there are no messages yet"}}
```
> Returns object Creates a mailbox object and checks for mail before returning.

**Comment by HughZurname** [comment]
@aelzhanova The reason it's not working is because the promise hasn't resolved when you are logging out the mailbox, I'll be implementing async/await as a solution to this, but for the time being you can use the following test setup as a workaround:

```javascript
Feature('Mailbox');

let mailbox

BeforeSuite((I) => {
    I.createMailbox('');
});

Before(function* (I) {
    mailbox = yield I.getMailbox();
});

Scenario('Check mailbox', function* (I) {
  console.log(mailbox)
});
```

**Comment by aelzhanova** [comment]
Thank you!
